settings:
  validator_address: "routervaloper****rh"
  debug_mode: false
  enable_orch_validation: true
  pager_duty_routing: "<pager-duty-routing>"
  orchestrator_health_endpoint: "http://<orch-host>:8001/health"
  schedule_interval_seconds: 600
  router_chain_lcd_url: "<router-chain-lcd>"