settings:
  operator_address: "routervaloper****k"
  validator_address: "router******l"
  orchestrator_address: "router******l"
  min_wallet_balance: "10ROUTE"
  debug_mode: false
  pager_duty_routing: "1dbf******9"
  orchestrator_health_endpoint: "http://IP:8001/health"
  schedule_interval_seconds: 5
  router_chain_lcd_url: "LCD_URL"