version: '3.8'

services:
  "router-chain-monitor":
    build: .
    ports:
      - "5000:5000"
    environment:
      - CONFIG_FILE_PATH=/usr/src/app/config.yml
    volumes:
      - .:/usr/src/app
      - ./config.yml:/usr/src/app/config.yml
